import Head from "next/head";
import Image from "next/image";

const links = [
  ["Home", "/"],
  ["Subscription", "/"],
  ["About", "/"],
];

export default function Home() {
  return (
    <div className="relative h-screen w-screen overflow-hidden text-white">
      <Head>
        <title>Anan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex absolute justify-end w-screen h-auto px-9 py-4 z-50">
        <div className="flex space-x-11 uppercase">
          {links.map((link) => {
            return (
              <a className="hover:text-ungu" href={link[1]}>
                {link[0]}
              </a>
            );
          })}
          <a href="/search" className="hover:text-ungu">
            <img src="./search.svg" />
          </a>
          <a href="/" className="hover:text-ungu">
            <img src="./user.svg" />
          </a>
        </div>
      </div>
      <div className="absolute top-0 left-0 z-0">
        <img className="w-auto h-screen" src="./frame10.png" />
      </div>
      <div className="flex relative flex-col w-screen h-screen justify-center items-center">
        <Image src="/home-hero.png" width={500} height={500} />
        <div className=" text-6xl font-semibold uppercase pb-4">
          Find your radionuclide
        </div>
        <div className="font-light capitalize pb-12">
          Search Engine For Easy Information
        </div>
        <div className="flex space-x-4 pb-8">
          <input
            className=" bg-ungu border-2 border-white  rounded-lg px-4 py-2 w-96"
            placeholder="Name and atomic number"
          />
          <button className="py-2 px-8 bg-white text-ungu hover:text-white hover:bg-transparent border-2 border-white rounded-lg">
            Get Started
          </button>
        </div>
        <a
          href="/search"
          className="uppercase font-medium text-xl hover:text-ungu"
        >
          Join Now
        </a>
      </div>
    </div>
  );
}
