import Head from "next/head";

const links = [
  ["Home", "/"],
  ["Subscription", "/"],
  ["About", "/"],
];

const data = [
  { nama: "nama" },
  { rad: "rad" },
  { half: "half" },
  { mass: "mass" },
  { shield: "shield" },
  { perusahaan: "perusahaan" },
  { alamat: "alamat" },
  { contact: "contact" },
];

export default function search() {
  return (
    <div className="relative h-screen w-screen overflow-hidden text-white">
      <Head>
        <title>Anan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img src="./toxic.png" className="absolute top-0 left-0 z-50" />
      <img src="./wing.png" className="absolute bottom-0 right-0 z-10" />
      <div className="flex absolute justify-end w-screen h-auto px-9 py-4 z-50">
        <div className="flex space-x-11 uppercase">
          {links.map((link) => {
            return (
              <a className="hover:text-ungu" href={link[1]}>
                {link[0]}
              </a>
            );
          })}
          <a href="/" className="hover:text-ungu">
            <img src="./search.svg" />
          </a>
          <a href="/" className="hover:text-ungu">
            <img src="./user.svg" />
          </a>
        </div>
      </div>
      <div className="absolute top-0 left-0 z-0">
        <img className="w-auto h-screen" src="./frame10.png" />
      </div>
      <div className="flex relative flex-col w-screen h-screen justify-center items-center z-40">
        <div className="flex space-x-4 pb-8">
          <input
            className=" bg-ungu border-2 border-white  rounded-lg px-4 py-2 w-96"
            placeholder="Name and atomic number"
          />
          <button className="py-2 px-8 bg-white text-ungu hover:text-white hover:bg-transparent border-2 border-white rounded-lg">
            Get Started
          </button>
        </div>
        <div className="border-4 border-white rounded-lg p-6">
          <div className="flex flex-col space-y-2">
            <p>Nama: {data.nama}</p>
            <p>Emmited Radiation: {data.rad}</p>
            <p>Half Time: {data.half}</p>
            <p>Atomic Mass: {data.mass}</p>
            <p>Shielding: {data.shield}</p>
            <p>Perusahaan: {data.perusahaan}</p>
            <p>Alamat: {data.alamat}</p>
            <p>Contact Person: {data.contact}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
